#
#  Copyright (C) 2003-2023, OFFIS e.V.
#  All rights reserved.  See COPYRIGHT file for details.
#
#  This software and supporting documentation were developed by
#
#    OFFIS e.V.
#    R&D Division Health
#    Escherweg 2
#    D-26121 Oldenburg, Germany
#
#  Module:  dcmnet
#
#  Author:  Marco Eichelberg, Joerg Riesmeier
#
# ----------------------------------------------------------
# 
#  Purpose: This configuration file is adapted from the original for the needs of DcmStoreService
#  For a more extensive description and a larger list of all presentation context options please refer to the original storescp.cfg file
#
#  Modified by: Giacomo Belli (2025)
#
# ============================================================================
[[TransferSyntaxes]]
# ============================================================================
#
# Please note that the Storage SCP will prefer the first entry in the selected
# list of transfer syntaxes that is acceptable, i.e. that it matches one of the
# transfer syntaxes proposed by the Storage SCU.
#

[Uncompressed]
TransferSyntax1 = LittleEndianExplicit
TransferSyntax2 = LittleEndianImplicit
TransferSyntax3 = BigEndianExplicit

[AnyTransferSyntax]
TransferSyntax1  = LittleEndianExplicit
TransferSyntax2  = LittleEndianImplicit
TransferSyntax3  = BigEndianExplicit
TransferSyntax4  = JPEGLossless:Non-hierarchical-1stOrderPrediction
TransferSyntax5  = JPEG2000
TransferSyntax6  = JPEG2000LosslessOnly


[Compressed]
TransferSyntax1  = JPEGLossless:Non-hierarchical-1stOrderPrediction
TransferSyntax2 =  JPEGLSLossless
TransferSyntax3 =  RLELossless
TransferSyntax4 =  JPEG2000LosslessOnly
TransferSyntax5 =  JPEG2000
TransferSyntax6 =  JPEG2000MulticomponentLosslessOnly
TransferSyntax7 =  JPEG2000Multicomponent

# ============================================================================
[[PresentationContexts]]
# ============================================================================


# ----------------------------------------------------------------------------

[MyDCMStorageSCP]
#
# Limited to a subset of non-retired and non-draft SOP Classes,
#
# Don't forget to support the Verification SOP Class.
#
PresentationContext1   = VerificationSOPClass\Uncompressed
#
# Accept image SOP classes with virtually any transfer syntax we know.
#
PresentationContext2   = CTImageStorage\Uncompressed
PresentationContext3   = ComputedRadiographyImageStorage\Uncompressed
PresentationContext4   = XRayRadiofluoroscopicImageStorage\Uncompressed
PresentationContext5   = XRayAngiographicImageStorage\Uncompressed
PresentationContext6   = DigitalXRayImageStorageForPresentation\Uncompressed
PresentationContext7   = DigitalXRayImageStorageForProcessing\Uncompressed
PresentationContext8   = MRImageStorage\Uncompressed
PresentationContext9   = UltrasoundImageStorage\Uncompressed
PresentationContext10  = NuclearMedicineImageStorage\AnyTransferSyntax
PresentationContext11  = PositronEmissionTomographyImageStorage\Uncompressed
PresentationContext12  = DigitalMammographyXRayImageStorageForPresentation\Uncompressed
PresentationContext13  = DigitalMammographyXRayImageStorageForProcessing\Uncompressed
PresentationContext14  = SecondaryCaptureImageStorage\AnyTransferSyntax
PresentationContext15  = UltrasoundMultiframeImageStorage\Uncompressed
PresentationContext16  = EnhancedCTImageStorage\Uncompressed
PresentationContext17  = EnhancedMRImageStorage\Uncompressed
PresentationContext18  = EnhancedMRColorImageStorage\Uncompressed
PresentationContext19  = EnhancedPETImageStorage\Uncompressed
PresentationContext20  = EnhancedUSVolumeStorage\Uncompressed
PresentationContext21  = EnhancedXAImageStorage\Uncompressed
PresentationContext22  = EnhancedXRFImageStorage\Uncompressed
PresentationContext23  = XRay3DAngiographicImageStorage\Uncompressed
PresentationContext24  = BreastProjectionXRayImageStorageForPresentation\Uncompressed
PresentationContext25  = BreastProjectionXRayImageStorageForProcessing\Uncompressed
PresentationContext26  = BreastTomosynthesisImageStorage\Uncompressed
PresentationContext27  = DigitalIntraOralXRayImageStorageForPresentation\Uncompressed
PresentationContext28  = DigitalIntraOralXRayImageStorageForProcessing\Uncompressed
PresentationContext29  = 1.2.840.10008.5.1.4.1.1.7.4\AnyTransferSyntax
#PresentationContext29  = MultiFrameTrueColorSecondaryCaptureImageStorage\AnyTransferSyntax
#PresentationContext    = \Uncompressed
#PresentationContext    = \Uncompressed
#PresentationContext    = \Uncompressed
#
# The following presentation contexts are for non-image SOP classes
# accept non-image SOP classes uncompressed or with zlib compression only.
# (some object may not fit into the PATIENT-STUDY-SERIES-INSTANCE model)
#
PresentationContext30  = EnhancedSRStorage\Uncompressed
PresentationContext31  = XRayRadiationDoseSRStorage\Uncompressed
PresentationContext32  = EnhancedXRayRadiationDoseSRStorage\Uncompressed
PresentationContext33  = PatientRadiationDoseSRStorage\Uncompressed
PresentationContext34  = RadiopharmaceuticalRadiationDoseSRStorage\Uncompressed
PresentationContext35  = PlannedImagingAgentAdministrationSRStorage\Uncompressed
PresentationContext36  = PerformedImagingAgentAdministrationSRStorage\Uncompressed
PresentationContext37  = MRSpectroscopyStorage\Uncompressed
PresentationContext38  = RawDataStorage\Uncompressed


# ============================================================================
[[Profiles]]
# ============================================================================

[MYPROFILE]
PresentationContexts = MyDCMStorageSCP

